version: "3.7"

services:
  redis:
    restart: always
    container_name: redis
    image: redis:7.2.3-alpine
    volumes:
      - redis-data:/data
      
  postgres-data:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-data
    restart: always
    environment:
      POSTGRES_DB: ${DB_DASHBOARD_DBNAME}
      POSTGRES_USER: ${DB_DASHBOARD_USER}
      POSTGRES_PASSWORD: ${DB_DASHBOARD_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15433:5432"

  postgres-manager:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-manager
    restart: always
    environment:
      POSTGRES_DB: ${DB_MANAGER_DBNAME}
      POSTGRES_USER: ${DB_MANAGER_USER}
      POSTGRES_PASSWORD: ${DB_MANAGER_PASSWORD}
    volumes:
      - postgres-manager-data:/var/lib/postgresql/data
    ports:
      - "${DB_MANAGER_PUBLISHED_PORT:-5432}:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "8889:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP/gRPC 接口預設埠
      - "6334:6334" # 複製／分片關係預設埠（如有需要）
    volumes:
      - qdrant-data:/qdrant/storage # 持久化資料儲存
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__WAL_ENABLED=true
      - QDRANT__STORAGE__WAL_PATH=/qdrant/storage/wal
      - QDRANT__STORAGE__SIZE_LIMIT=20GB # 預估大小，依需求調整
      # 啟用 API key 驗證
      - QDRANT__SERVICE__API_KEY_ENABLED=true
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

networks:
  default:
    name: br_dashboard
    external: true

volumes:
  redis-data:
    name: redis_data
  postgres-data:
    name: postgres_data
  postgres-manager-data:
    name: postgres_manager_data
  pgadmin-data:
    name: pgadmin_data
  qdrant-data:
    name: qdrant_data
